### ISSUE TITLE
New folder creation, folder_rendering schema is not assigned

### ISSUE THREAD

**Issue by adambertalan** [edraj/dmart#253]
I followed the steps in the readme to setup dmart using containers.

I opened the admin UI (localhost:8000) and then created a new space.

Within that space I tried to create a new folder with the following parameters:

**Resource type:** folder
**Schema:** folder_rendering
**Shortname:** test

The folder is successfully created however in the table it says that the newly created folder's schema is "**not_applicable**"

Because of this issue I cannot edit the payload of the folder, I can only edit the meta.

I tried to work around this issue and added the following lines to the folder's meta JSON:

```
"payload": {
    "content_type": "json",
    "schema_shortname": "folder_rendering"
  }
```

When I try to save the modified JSON I get the following error:

```
{
 "status": "failed",
 "error": {
  "code": 99,
  "message": "'body'",
  "stack": [
   {
    "file": "/home/backend/main.py",
    "function": "middle",
    "line": 166
   },
   {
    "file": "/home/backend/utils/middleware.py",
    "function": "__call__",
    "line": 34
   },
   {
    "file": "/home/backend/api/managed/router.py",
    "function": "serve_request",
    "line": 827
   },
   {
    "file": "/home/backend/models/core.py",
    "function": "update_from_record",
    "line": 215
   },
   {
    "file": "/home/backend/models/core.py",
    "function": "update",
    "line": 66
   }
  ]
 }
}
```

Also I notied that the sample data (loaded in the container setup guide) also have spaces with folders that have the "**not_applicable**" schema, for example personal/people.

**Comment by splimter** [comment]
Hello @adambertalan please check again against the new version, the issue should be resolved.

**Comment by adambertalan** [comment]
Hi  @splimter!
Thank you for the response,
I tried it again but the issue is still there

Here is a youtube video link where I reproduce the issue: https://youtu.be/Yx-_wPN_M-s
