### ISSUE TITLE
Admin UI crash when opening a folder_rendering schema

### ISSUE THREAD

**Issue by adambertalan** [edraj/dmart#254]
Steps to reproduce the issue:

1. Follow the steps in the container setup guide
2. Open the admin UI (localhost:8000)
3. Open the Personal space from the left menu
4. Open the schema folder
5. Click on the folder_rendering schema in the table

The content is displayed but the admin UI shows a loading progress bar at the top until the **browser crashes**.

**Comment by splimter** [comment]
Hello @adambertalan please check again against the new version, the issue should be resolved.

**Comment by adambertalan** [comment]
Hi @splimter!
Thank you for the response!
Unfortunately the issue is still there.

Here is a youtube video link where I reproduce the issue: https://youtu.be/VRB_Up07Djw
